monash-human-power/MHP-website

- package-lock.json
Bumped up the version of certain modules. Fixed security vulnerabilities.
> Bump Modules

- src/components/index/contact_form.js
- src/components/index/sponsors.js
- src/components/index/subteams.js
- src/markdown/index.md
- src/markdown/team.md
- src/pages/bike.js
- src/pages/index.js
- static/admin/config.yml
Add CMS functionality to all pages with text. Other than that small clean up changes.
Kinda hard to test this one before it gets merged into the master. In the meantime checkout the 404 page [here
](https://mhp-test.netlify.app/404)
> Blake haydon/add cms all pages

- src/components/teampage_infoblock.js
- src/markdown/team.md
- src/pages/team.js
- static/admin/config.yml
> Created team page code

- src/components/header.js
- src/markdown/index.md
> Blake haydon/into prod

- src/markdown/index.md
Hot fix to remove the team button
> Remove team button

- static/admin/config.yml
Add the ability to have no button in netlify CMS
> Set button text to not required (for no button)

- src/components/index/subteams.js
- src/components/teampage_infoblock.js
- src/markdown/team.md
- src/pages/team.js
- static/admin/config.yml
> Angie aulia/teampage

- .all-contributorsrc
- README.md
- package-lock.json
- package.json
Adds contributions as per the All Contributors spec.
> Add all contributions

- src/pages/index.js
The contact form seems to be broken. While we figure out whats wrong, we'll temporarily hide it.
`gatsby develop`, contact form should not be visible.
> Hide contact form

- src/components/seo.js
- src/markdown/404.md
- src/markdown/bike.md
- src/markdown/index.md
- src/markdown/subteams.md
- src/markdown/team.md
- src/pages/404.js
- src/pages/bike.js
- src/pages/index.js
- src/pages/subteams.js
- src/pages/team.js
- static/admin/config.yml
This PR does a couple of best practices that should help with SEO. 
- Site maps were supplied to Bing and Google
- Added Yandex verification
- Adds titles that are better for search
- Adds the option to change the description of a page in the CMS
_index page_
_bikes page_
Check out the PR link or run `gatsby develop` locally
> Improve SEO Rankings

- src/components/seo.js
This PR resolves the issue with the incorrect yandex-verification meta tag in #68.
> Update `yandex-verification` Meta Tag

- src/components/footer.js
This PR adds an acknowledgement of country to the bottom of the page.
> Add Acknowledgement of Country

- src/markdown/subteams.md
- src/pages/index.js
> Remove MHP Recruitment Info

- src/components/button.js
- src/components/header.js
- src/components/index/sponsors.js
- src/components/index/subteams.js
- src/components/info_block.js
- src/components/socials.js
- src/components/subpage_heading.js
- src/markdown/index.md
- src/markdown/outreach.md
- src/pages/outreach.js
- src/pages/subteams.js
- src/pages/team.js
- src/styles/global.css
- static/admin/config.yml
This PR adds the outreach page. The content is not finished however the main outline is complete.
[Click here to see the live demo](https://deploy-preview-82--mhp-test.netlify.app/) or run locally using instructions in the readme
> Add outreach page

- src/components/footer.js
- src/markdown/socials.md
The pull request changes the links of facebook and instagram (footer and header) 
1. run yarn develop on VS code 
2. click on the facebook and instagram header 
3. check that it links to appropriate page (facebook or instagram)
4. repeat steps 2 and 3 for footer
> Ctia0007/updating links to facebook and instagram 

- src/components/footer.js
- src/components/header.js
- src/components/index/sponsors.js
- src/components/link.js
- src/markdown/bike.md
- src/markdown/index.md
- src/pages/bike.js
Basic aesthetic changes to the bike page on MHP website as it was asked. 
N/A
> bike page update

- src/markdown/index.md
- src/pages/index.js
Activated and updated recruitment link for new round of recruiting. 
- added the join us field on main page  (shown below)
- both join us in header and footer will open up the google form in another page
https://user-images.githubusercontent.com/81912681/166856736-5e03b63a-bbd7-4f31-8b5a-f0a9694b1cf3.mov
run `yarn develop` and you should be able to see the website with the changes I made.
> Activated and updated recruitment link

- src/markdown/subteams.md
Adds Rider Dev expression of interest link.
`yarn develop`
> Add rider dev EOI link

- src/markdown/index.md
- src/pages/index.js
Updating Recruitment links and info for July 2022 recruitment round.
1) run `yarn develop`
2) Confirm the 'Join Us' button at the top navigation bar and the 'Apply here' button on main page point to correct 2022 Recruitment round google form.
> Update recuitment info

- src/markdown/index.md
Change the trailer in the home page to the final version
Just build as normal.
> Add final version of MHP trailer

- static/admin/config.yml
Update the Netlify CMS schema for the new and updated pages
Recruitment page:
Build as normal.
> Update Netlify CMS schema

- src/components/info_block.js
- src/markdown/joinUs.md
- src/pages/blog.js
- src/pages/index.js
- static/admin/config.yml
- Fix buttons on info block (see screenshot)
- make recruitment process grid content field optional
- Add some text on blog page if there are no posts to show
Build as normal
> Some website improvements and bugfixes

- .husky/pre-commit
- README.md
- package.json
- yarn.lock
Revamp contribution guide on README, splitting to those who just want to add content via CMS and those who want to change the code
> Revamp contribution guide on README

- src/components/review.js
- src/components/text_grid.js
This is a continuation of #190 as I noticed that I completely forgot the grid in outreach page.
> Do not draw shadows for review cell

- static/admin/config.yml
Add a field in CMS schema so you can edit the image in about page.
> Add ability to change image in about page using CMS

- static/admin/config.yml
Since Yarra Energy website is down, I've relaxed the requirement for each sponsor to have its own link
> Make sponsor field link optional

- src/components/header.js
- src/components/socials.js
- src/markdown/socials.md
- static/admin/config.yml
Also remove socials link from the header since they're kinda getting crowded to show them all on the header.
> Add YouTube link to socials
